- name: Deploy traefik
  hosts: general
  vars:
    workdir: "/home/{{ ansible_user }}/docker/traefik/"
  tasks:
    - name: Copy files
      copy:
        src: ../../docker/traefik/
        dest: "{{ workdir }}"

    - name: Restart containers
      community.docker.docker_compose:
        project_src: "{{ workdir }}"
        build: false
        state: present
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output
