services:
  proxy:
    image: traefik:3.0
    ports:
      - "80:80"
      - "443:443"
      - "8082:8080"
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
